# Generated by Django 6.0 on 2025-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
